stages:
  data_ingestion:
    cmd: python src/myFashionRecommender/pipeline/stage_01_data_ingestion.py
    deps:
      - src/myFashionRecommender/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/images

  prepare_base_model:
    cmd: python src/myFashionRecommender/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/myFashionRecommender/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - WEIGHTS
    outs:
      - artifacts/prepare_base_model

  feature_extraction:
    cmd: python src/myFashionRecommender/pipeline/stage_03_feature_extraction.py
    deps:
      - src/myFashionRecommender/pipeline/stage_03_feature_extraction.py
      - config/config.yaml
      - artifacts/data_ingestion/images
      - artifacts/prepare_base_model/base_model_updated.h5
    outs:
      - artifacts/features
      - artifacts/filenames
