artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # source_url: https://drive.google.com/file/d/1rz4hNrQYyqqVpKeqtPliQUMbGh_FmPhh/view?usp=sharing # Link to download smaller version of the data
  source_url: https://drive.google.com/file/d/1NgJekF3f6fKg6Ve_l0qtm0FaDPBzHgkn/view?usp=sharing # Link to download the full data
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

feature_extraction:
  features_root_dir: artifacts/features
  files_root_dir: artifacts/filenames
  local_data_file: artifacts/data_ingestion/images

flask_app:
  extracted_features_path: artifacts/features/model.pkl
  filenames_path: artifacts/filenames/filenames.pkl
  model_path: artifacts/prepare_base_model/base_model_updated.h5
  knn_neighbors: 6
  knn_metric: euclidean
  knn_algorithm: brute
